### ISSUE TITLE
We would like to message you.

### ISSUE THREAD

**Issue by johnklipi** [samuelyuan/PolytopiaMapEditor#1]
Hello! We are group of Polytopia modders which would like to have a conversation with you. Please, consider joining here and dming johnklipi: https://discord.gg/RHZDGe7vgJ. Have a good day!

**Comment by samuelyuan** [comment]
Is there any topics you would like to discuss?

**Comment by johnklipi** [comment]
Not really, we are just searching for coders in our current project. We are doing private server with ingame built in mod loader and map maker. If you are interested join here: https://discord.gg/eWPdhWtfVy (link before is not working)

**Comment by johnklipi** [comment]
Hi again. Yes, we have a topic to discuss, and it is about game states. Maybe you know how to serialize a state in the string? Please, dm johnklipi here if you decide to help us: https://discord.gg/eWPdhWtfVy
