### ISSUE TITLE
Needs an update

### ISSUE THREAD

**Issue by Seventeen999** [samuelyuan/PolytopiaMapEditor#2]
After the release of the Aquarion update, the editor unfortunately no longer seems to work. Are you planning on releasing an update to make it compatible with the latest version of Polytopia? Really enjoyed using this while it worked, it'd be a shame to lose it.

**Comment by samuelyuan** [comment]
I updated the code to be compatible with the latest version of Polytopia, which is version 105. The tile data has an extra field that was added.

**Comment by Seventeen999** [comment]
Perfect, thank you so much!
